name: Update Motivational Quote
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Quote and Update README
        run: |
          QUOTE=$(curl -s "https://api.quotable.io/random" | jq -r '.content')
          if [ -z "$QUOTE" ]; then
            echo "Failed to fetch quote"
            exit 1
          fi
          sed -i "s|<!-- QUOTE -->.*|<!-- QUOTE --> \"$QUOTE\"|" README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated Motivational Quote" || echo "No changes to commit"
          git push || echo "No changes to push"
